website/apps/gallery/urls.py
from django.urls import path

from .views import GalleryView, ListGalleriesView

urlpatterns = [
    path("", ListGalleriesView.as_view(), name="galleries"),
    path("<slug:slug>/", GalleryView.as_view(), name="gallery_detail"),
]

website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

from website.apps.flatpages_ckeditor import views

urlpatterns = (
    [
        # django-related options
        path("admin/", admin.site.urls),
        path("i18n/", include("django.conf.urls.i18n")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
)

urlpatterns += i18n_patterns(
    path(_("about/"), views.flatpage, {"url": "/about/"}, name="about"),
    path("", include("website.apps.gallery.urls")),
)

website/apps/gallery/models.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import get_language
from django.utils.translation import gettext_lazy as _
from django_resized import ResizedImageField
from parler.models import TranslatableModel, TranslatedFields, TranslationDoesNotExist


class Gallery(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(
            max_length=1024,
            help_text=_("Title of your gallery."),
            verbose_name=_("Title"),
        ),
        slug=models.SlugField(
            max_length=1024,
            blank=True,
            null=False,
            unique=True,
            help_text=_(
                "Slug is autogenerated on save. You don't have to fill this field. You can however update it if it don't fits your needs."
            ),
            verbose_name=_("Slug"),
        ),
        short_description=models.CharField(
            max_length=1024,
            help_text=_("Short description that will be displayed on gallery list."),
            verbose_name=_("Short description"),
            blank=True,
            null=True,
        ),
        content=RichTextField(
            help_text=_("Description of the gallery."),
            verbose_name=_("Content"),
            blank=True,
        ),
    )

    is_published = models.BooleanField(
        default=False,
        verbose_name=_("Is published?"),
        help_text=_(
            "If this is true, then the gallery will be published (available through their url)."
        ),
    )

    have_a_hash_protection = models.BooleanField(
        default=False,
        verbose_name=_("Gallery is private"),
        help_text=_(
            "If this is true, then you can only visit the gallery using its private link."
        ),
    )

    url_hash = models.CharField(max_length=255, editable=False, blank=True, null=True)

    is_password_protected = models.BooleanField(
        default=False,
        verbose_name=_("Gallery is password-protected"),
        help_text=_(
            'If this is true, then you can visite the gallery only if you have the password. The gallery will still be listed on the main gallery list, and it\'s short description will be displayed too (unless "Gallery is private" is checked), but no image will be displayed unless the password is submitted.'
        ),
    )

    password = models.CharField(
        max_length=1024,
        verbose_name=_("Password"),
        help_text=_(
            'If "access by password only" is set to True, then you can put your password here.'
        ),
        null=True,
        blank=True,
    )

    date_added = models.DateTimeField(
        auto_now_add=True, editable=False, verbose_name=_("Added date")
    )
    date_edit = models.DateTimeField(
        editable=False, null=True, verbose_name=_("Last edit date")
    )
    added_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        editable=False,
        blank=True,
        null=True,
        verbose_name=_("Author"),
    )
    license = models.ForeignKey(
        "License",
        on_delete=models.SET_NULL,
        verbose_name=_("License"),
        blank=True,
        null=True,
    )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        try:
            if self.title:
                if self.slug == "":
                    self.slug = slugify(self.title)
        except TranslationDoesNotExist:
            pass
        if self.id is not None:
            self.date_edit = timezone.now()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        lang = get_language()
        return reverse(
            "gallery_detail",
            kwargs={"slug": self.translations.get(language_code=lang).slug},
        )

    class Meta:
        verbose_name = _("Gallery")
        verbose_name_plural = _("Galleries")


class Image(TranslatableModel):
    image = ResizedImageField(upload_to="galleries/", verbose_name=_("Image"))

    order = models.PositiveSmallIntegerField(
        default=0,
        blank=False,
        null=False,
    )

    translations = TranslatedFields(
        short_description=models.CharField(
            max_length=1024,
            help_text=_("Short description that will be displayed below the image."),
            verbose_name=_("Short description"),
            null=True,
            blank=True,
        )
    )
    gallery = models.ForeignKey(
        "Gallery", on_delete=models.CASCADE, verbose_name=_("Gallery")
    )
    license = models.ForeignKey(
        "License",
        on_delete=models.SET_NULL,
        verbose_name=_("License"),
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")
        ordering = ("order",)


class License(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(
            max_length=1024,
            help_text=_("The name of the license."),
            verbose_name=_("Name"),
        ),
        license=models.TextField(
            help_text=_("Text of the license."), verbose_name=_("License")
        ),
    )
    url = models.URLField(
        max_length=1024, help_text=_("Homepage of the license."), verbose_name=_("URL")
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("License")
        verbose_name_plural = _("Licenses")

website/apps/gallery/forms.py
from django import forms


class GalleryPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput())

website/apps/gallery/views.py
from django.http import Http404
from django.views.generic import DetailView, ListView
from parler.views import TranslatableSlugMixin

from .forms import GalleryPasswordForm
from .models import Gallery


class ListGalleriesView(ListView):
    model = Gallery
    paginate_by = 5
    context_object_name = "galleries"
    queryset = Gallery.objects.filter(
        is_published=True, have_a_hash_protection=False
    ).order_by("-date_added")


class GalleryView(TranslatableSlugMixin, DetailView):
    model = Gallery
    context_object_name = "gallery"

    def post(self, request, *args, **kwargs):
        password_form = GalleryPasswordForm(self.request.POST or None)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        if password_form.is_valid():
            try:
                session_gallery_slug = f"gallery_{self.object.slug}"
                if password_form.cleaned_data["password"] == self.object.password:
                    request.session[session_gallery_slug] = True
                    context["session_gallery_valid"] = True
            except Gallery.DoesNotExist:
                return "nope"
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.object.is_published:
            raise Http404()

        # has url hash?
        context["is_protected_by_hash"] = False
        context["url_has_a_hash"] = False
        if self.object.have_a_hash_protection:
            context["is_protected_by_hash"] = True
            for get_hash in self.request.GET.keys():
                if get_hash == self.object.url_hash:
                    context["url_has_a_hash"] = True

        # has password?
        if self.object.is_password_protected:
            context["password_form"] = GalleryPasswordForm()
            session_gallery_slug = f"gallery_{self.object.slug}"
            if session_gallery_slug not in self.request.session:
                self.request.session[session_gallery_slug] = False
            context["session_gallery_valid"] = self.request.session[
                session_gallery_slug
            ]

        return context

website/apps/gallery/templates/gallery/gallery_detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load thumbnail %}
{% load i18n %}

{% block custom_css %}
  <link rel="stylesheet" href="{% static "css/photoswipe.css" %}">
  <link rel="stylesheet" href="{% static "css/photoswipe-dynamic-caption-plugin.css" %}">
{% endblock custom_css %}

{% block title %}{% translate "Gallery" %} | {{ gallery.title }}{% endblock title %}
{% block h1 %}{{ gallery.title }}{% endblock h1 %}

{% block main %}
  {% if is_protected_by_hash and url_has_a_hash or not is_protected_by_hash %}

    {% if gallery.is_password_protected and session_gallery_valid or not gallery.is_password_protected %}

      {% include "gallery/gallery_images.html" %}
      {% if gallery.license %}
        <details>
          <summary><i>{% translate "All images on this gallery (except the ones that have another license) are on license " %}</i> {{ gallery.license.name }}</summary>
          <p><i><a href="{{ gallery.license.url }}">{% translate "More informations" %}</a></i></p>
          <pre>
            {{ gallery.license.license }}
          </pre>
        </details>
      {% endif %}
    {% else %}
      <p>{% translate "This gallery is protected by a password." %}</p>
      <form action="{% url "gallery_detail" gallery.slug %}" method="post">
        {% csrf_token %}
        {{ password_form.as_p }}
        <input type="submit" value="Submit">
      </form>
    {% endif %}

  {% else %}
    <p>
      {% translate "This gallery is protected and is only accessible by using the secret link." %}
    </p>
  {% endif %}
{% endblock main %}

{% block custom_js %}
  <script type="module">
    import PhotoSwipeLightbox from '{% static "js/photoswipe-lightbox.esm.min.js" %}';
    import PhotoSwipeDynamicCaption from '{% static "js/photoswipe-dynamic-caption-plugin.esm.js" %}';
    const lightbox = new PhotoSwipeLightbox({
      gallery: '#{{ gallery.slug }}',
      children: 'a',
      pswpModule: () => import('{% static "js/photoswipe.esm.min.js" %}'),
      paddingFn: (viewportSize) => {
        return {
          top: 30, bottom: 30, left: 70, right: 70
        }
      },
    });
    const captionPlugin = new PhotoSwipeDynamicCaption(lightbox, {
      type: 'auto',
    });
    lightbox.init();
  </script>
{% endblock custom_js %}

website/apps/gallery/templates/gallery/gallery_images.html
{% load humanize %}
{% load thumbnail %}
{% load i18n %}

<section>

  <h2>
    {% if gallery.is_password_protected %}<span class="help" title="{% translate "This gallery is protected by a password." %}">🔒</span>{% endif %}
    <a href="{% url "gallery_detail" gallery.slug %}">{{ gallery.title }}</a>
  </h2>

  <blockquote>
    <span class="help" title="{{ gallery.date_added }}">
      {% translate "Published" %} {{ gallery.date_added|naturaltime }}
    </span>
    {% translate "by" %} {{ gallery.added_by }}{% if gallery.date_edit %},
      <span class="help" title="{{ gallery.date_edit }}">{% translate "updated" %} {{ gallery.date_edit|naturaltime }}</span>{% endif %}{% if gallery.is_password_protected and session_gallery_valid or not gallery.is_password_protected  %}, {{ gallery.image_set.all|length }} {% translate "image" %}{{ gallery.image_set.all|length|pluralize }}{% endif %}.
    {% if gallery.have_a_hash_protection %}
      <br /><i>{% translate "This gallery is private (it has a private url and does not appear on the gallery list)." %}</i>
    {% endif %}
  </blockquote>

  {{ gallery.content|safe }}

  <article class="gallery" id="{{ gallery.slug }}">
    {% for image in gallery.image_set.all %}
      <a href="{{ image.image.url }}" data-pswp-width="{{ image.image.width|cut:" " }}" data-pswp-height="{{ image.image.height|cut:" " }}" data-cropped="true">
        <figure class='gallery-image' >
          {% if item.image|is_portrait %}
            {% thumbnail image.image "600" as thumb %}
              <img src="{{ thumb.url }}" alt="{{ image.short_description }}" title="{{ image.short_description }}" loading="lazy" />
            {% endthumbnail %}
          {% else %}
            {% thumbnail image.image "x400" as thumb %}
              <img src="{{ thumb.url }}" alt="{{ image.short_description }}" title="{{ image.short_description }}" loading="lazy" />
            {% endthumbnail %}
          {% endif %}
          {% if image.short_description %}
            <figcaption>{{ image.short_description }}</figcaption>
          {% endif %}
          {% if image.license %}
            <figcaption class="small">
              <i>{% translate "The previous image is on license " %}</i> {{ gallery.license.name }} <i>(<a href="{{ gallery.license.url }}">{% translate "More informations" %}</a>)</i>.
            </figcaption>
          {% endif %}
        </figure>
      </a>
    {% endfor %}
  </article>
</section>

website/apps/gallery/templates/gallery/gallery_list.html
{% extends "base.html" %}
{% load humanize %}
{% load thumbnail %}
{% load i18n %}

{% block title %}{% translate "Galleries" %}{% endblock title %}
{% block h1 %}{% translate "Galleries" %}{% endblock h1 %}

{% block main %}
  {% for gallery in galleries %}

    <article class="gallery-in-list">
      <h2>
        {% if gallery.is_password_protected %}<span class="help" title="{% translate "This gallery is protected by a password." %}">🔒</span>{% endif %}
        <a href="{% url "gallery_detail" gallery.slug %}">{{ gallery.title }}</a>
      </h2>
      <blockquote>
        <span class="help" title="{{ gallery.date_added }}">
          {% translate "Published" %} {{ gallery.date_added|naturaltime }}
        </span>
        {% translate "by" %} {{ gallery.added_by }}{% if gallery.date_edit %},
          <span class="help" title="{{ gallery.date_edit }}">{% translate "updated" %} {{ gallery.date_edit|naturaltime }}</span>{% endif %}{% if gallery.is_password_protected and session_gallery_valid or not gallery.is_password_protected  %}, {{ gallery.image_set.all|length }} {% translate "image" %}{{ gallery.image_set.all|length|pluralize }}{% endif %}.
        {% if gallery.have_a_hash_protection %}
          <br /><i>{% translate "This gallery is private (it has a private url and does not appear on the gallery list)." %}</i>
        {% endif %}
      </blockquote>
      {% if gallery.short_description %}
        <p>{{ gallery.short_description }}</p>
      {% else %}
        {% translate "No description." %}
      {% endif %}
      <span>
        {% for image in gallery.image_set.all %}
          {% if not gallery.short_description or forloop.counter <= 5 and not gallery.is_password_protected %}
            <img src="{% thumbnail image.image "120x120" as thumb %}{{ thumb.url }}{% endthumbnail %}" alt="{{ image.short_description }}" title="{{ image.short_description }}" loading="lazy" />
          {% endif %}
        {% endfor %}
        {% if gallery.short_description and gallery.image_set.all.count > 5 %}
          <p>... {% translate "And more!" %}</p>
        {% endif %}
      </span>
    </article>

  {% empty %}
    <p>
      {% translate "No gallery for now." %}
    </p>
  {% endfor %}

  {% include "pagination.html" %}
{% endblock main %}

website/apps/gallery/templates/gallery/upload_multiple_files.html
{% extends "admin/change_list.html" %}
{% load i18n %}

{% block title %}{% translate "Upload multiple files" %} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
{% endblock breadcrumbs %}

{% block object-tools %}
{% endblock object-tools %}

{% block search %}
{% endblock %}

{% block result_list %}
{% endblock result_list %}

{% block pagination %}
{% endblock pagination %}

{% block content %}
  <div id="content-main">
    <h1>{% translate "Add multiple files" %}</h1>
    <form enctype="multipart/form-data" method="post" action=".">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="{% translate "Send" %}" />
    </form>
  </div>
{% endblock content %}